### ISSUE TITLE
Do students need to see the (Teachers) tab?

### ISSUE THREAD

**Issue by ilyankou** [ram8647/gcb-clone-v111#10]
The (Teachers) tab is visible to both students and teachers.

When I am logged in as a teacher, when I go to that tab, I see this:
![screen shot 2017-06-19 at 17 25 51](https://user-images.githubusercontent.com/10443203/27306671-7da8c3f0-5514-11e7-8f6d-536f2a34590c.png)

When I am logged in as a student, when I click on (Teachers), I see the general course info (which makes no sense):
![screen shot 2017-06-19 at 17 25 24](https://user-images.githubusercontent.com/10443203/27306679-8c257cc0-5514-11e7-9c7b-0d140c47876d.png)

It also seems like I don't see my email and 'Logout' option when I'm a Teacher (upper right corner).

**Comment by ilyankou** [comment]
This one is tricky because the template variables in `views/base_course.html` can only tell if you're admin or no (from `controller/utils.py`, there are variables `is_course_admin` or `is_super_admin`).

To determine if you're a teacher, you need to import TeacherRights from `modules/teacher/teacher_entity.py`. You can definitely import it when you are in other modules, but I am not sure one can do this from outside.

Still working on it.

**Comment by bhoffman0** [comment]
Try using the new registration form fields which are in the Student entity (additional_fields.name= "usertype" && additional_fields.value= "teacher"). Since this is not in the teacher module, it should be accessible in utils.py. The TeacherRights entity is for the list of teachers approved to access the Teacher Dashboard (the list is manually created). The Student entity tracks whether a user checked off teacher or student on the new registration form. It makes more sense to use the Student entity additional_fields, since we want teachers not approved for the dashboard to still see the (Teachers) tab and get that message about how to get approved to use it.

**Comment by bhoffman0** [comment]
Tab was moved to teacher side of the course.
